version: '3'
name: course
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8080
    restart: always

  proxy:
    image: nginx
    ports:
      - 8002:8000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - backend

  frontend:
    container_name: front
    image: nginx:alpine3.19-slim
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "1234:80"
    depends_on:
      - backend
      - proxy
